// GENERATED by scripts/riskometer/refresh.mjs from official riskometer disclosures. Do not edit by hand.
// Each entry: scheme-level risk level, as-of (portfolio) date and the official source URL.
import type { RiskometerEntry } from "./riskometer";

export const RISKOMETER_ENTRIES: readonly RiskometerEntry[] = /* DATA-START */[
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Aggressive Hybrid Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Arbitrage fund",
  "level": "Low",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Banking & Financial Services Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Banking and PSU Debt Fund",
  "level": "Moderate",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP BSE SENSEX Next 30 Index Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Business Cycle Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Corporate Bond Fund",
  "level": "Low to Moderate",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Credit Risk Fund",
  "level": "Moderately High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP CRISIL-IBX 50:50 Gilt Plus SDL - April 2033 Index Fund",
  "level": "Moderate",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Dynamic Asset Allocation Fund",
  "level": "Moderately High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP ELSS Tax Saver Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Equity Savings Fund",
  "level": "Moderate",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Flexi Cap Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Focused Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Gilt Fund",
  "level": "Moderate",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Global Clean Energy Overseas Equity Omni FoF",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Gold ETF Fund of Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Healthcare Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Income Plus Arbitrage Omni FoF",
  "level": "Moderate",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP India T.I.G.E.R. Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Large & Mid Cap Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Large Cap Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Midcap Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Multi Asset Allocation Fund",
  "level": "High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Natural Resources And New Energy Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Nifty 50 Equal Weight Index Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Nifty 50 Index Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Nifty Bank Index Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Nifty Midcap 150 Quality 50 Index Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Nifty Next 50 Index Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Nifty Private Bank Index Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Nifty SDL Plus G-Sec Jun 2028 30:70 Index Fund",
  "level": "Low to Moderate",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Nifty SDL Plus G-Sec Sep 2027 50:50 Index Fund",
  "level": "Low to Moderate",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Nifty Smallcap250 Quality 50 Index Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Nifty Top 10 Equal Weight Index Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Overnight Fund",
  "level": "Low",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Quant Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Short Term Fund",
  "level": "Moderate",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Small Cap Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP US Specific Debt Passive FoF",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP US Specific Equity Omni FoF",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP Value Fund",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP World Gold Mining Overseas Equity Omni FoF",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "DSP Mutual Fund",
  "fund": "DSP World Mining Overseas Equity Omni FoF",
  "level": "Very High",
  "asOf": "2026-03-31",
  "sourceUrl": "https://www.dspim.com/media/pages/mandatory-disclosures/annual-risk-o-meter-disclosure/4729ddd053-1776243648/annual-disclosure-of-riskometers-dsp-mf-as-at-march-31-2026.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Aggressive Hybrid Fund (Formerly Known as Principal Hybrid Equity Fund)",
  "level": "High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Arbitrage Fund(Formerly Known as Prinicpal Arbitrage Fund)",
  "level": "Low",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Business Cycle Fund",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Conservative Hybrid Fund (Formerly Known as Sundaram Debt Oriented Hybrid Fund)",
  "level": "Moderate",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Consumption Fund (Formerly Known as Sundaram Rural and Consumption Fund)",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Corporate Bond Fund",
  "level": "Moderate",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Dividend Yield Fund (Formerly Known as Principal Dividend Yield Fund)",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram ELSS Tax Saver Fund",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Equity Savings Fund (Formerly Known as Principal Equity Savings Fund)",
  "level": "Moderate",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Flexicap Fund",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Focused Fund (Formerly Known as Principal Focused Multicap Fund)",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Large Cap Fund ( Formerly Know as Sundaram Blue Chip Fund)",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Liquid Fund (Formerly Known as Principal Cash Management Fund)",
  "level": "Low to Moderate",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Mid Cap Fund",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Money Market Fund",
  "level": "Low to Moderate",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Multi Asset Allocation Fund",
  "level": "High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Multi Cap Fund (Formerly Known as Principal Multi Cap Growth Fund)",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Multi-Factor Fund",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Overnight Fund",
  "level": "Low",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Services Fund",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Small Cap Fund",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 },
 {
  "amc": "Sundaram Mutual Fund",
  "fund": "Sundaram Value Fund",
  "level": "Very High",
  "asOf": "2026-01-31",
  "sourceUrl": "https://www.sundarammutual.com/pdf2/2026/Risk_Meter/Change_in_Risk_O_Meter_Jan_26.pdf"
 }
]/* DATA-END */;
