/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DataStatusRouteImport } from './routes/data-status'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as GrievanceRouteImport } from './routes/grievance'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RiskAssessmentRouteImport } from './routes/risk-assessment'
import { Route as RiskProfileRouteImport } from './routes/risk-profile'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SipCalculatorRouteImport } from './routes/sip-calculator'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as FundsIndexRouteImport } from './routes/funds.index'
import { Route as FundsFundSlugRouteImport } from './routes/funds.$fundSlug'
import { Route as ApiPublicFundSyncRouteImport } from './routes/api/public/fund-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DataStatusRoute = DataStatusRouteImport.update({
  id: '/data-status',
  path: '/data-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRoute = GrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAssessmentRoute = RiskAssessmentRouteImport.update({
  id: '/risk-assessment',
  path: '/risk-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskProfileRoute = RiskProfileRouteImport.update({
  id: '/risk-profile',
  path: '/risk-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SipCalculatorRoute = SipCalculatorRouteImport.update({
  id: '/sip-calculator',
  path: '/sip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsIndexRoute = FundsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FundsRoute,
} as any)
const FundsFundSlugRoute = FundsFundSlugRouteImport.update({
  id: '/$fundSlug',
  path: '/$fundSlug',
  getParentRoute: () => FundsRoute,
} as any)
const ApiPublicFundSyncRoute = ApiPublicFundSyncRouteImport.update({
  id: '/api/public/fund-sync',
  path: '/api/public/fund-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/data-status': typeof DataStatusRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/funds': typeof FundsRouteWithChildren
  '/goals': typeof GoalsRoute
  '/grievance': typeof GrievanceRoute
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/risk-profile': typeof RiskProfileRoute
  '/services': typeof ServicesRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/funds/$fundSlug': typeof FundsFundSlugRoute
  '/funds/': typeof FundsIndexRoute
  '/api/public/fund-sync': typeof ApiPublicFundSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/data-status': typeof DataStatusRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/goals': typeof GoalsRoute
  '/grievance': typeof GrievanceRoute
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/risk-profile': typeof RiskProfileRoute
  '/services': typeof ServicesRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/funds/$fundSlug': typeof FundsFundSlugRoute
  '/funds': typeof FundsIndexRoute
  '/api/public/fund-sync': typeof ApiPublicFundSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/data-status': typeof DataStatusRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/funds': typeof FundsRouteWithChildren
  '/goals': typeof GoalsRoute
  '/grievance': typeof GrievanceRoute
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/risk-profile': typeof RiskProfileRoute
  '/services': typeof ServicesRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/funds/$fundSlug': typeof FundsFundSlugRoute
  '/funds/': typeof FundsIndexRoute
  '/api/public/fund-sync': typeof ApiPublicFundSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/data-status'
    | '/explore'
    | '/faq'
    | '/feedback'
    | '/funds'
    | '/goals'
    | '/grievance'
    | '/learn'
    | '/privacy'
    | '/process'
    | '/resources'
    | '/risk-assessment'
    | '/risk-profile'
    | '/services'
    | '/sip-calculator'
    | '/terms'
    | '/transparency'
    | '/funds/$fundSlug'
    | '/funds/'
    | '/api/public/fund-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/data-status'
    | '/explore'
    | '/faq'
    | '/feedback'
    | '/goals'
    | '/grievance'
    | '/learn'
    | '/privacy'
    | '/process'
    | '/resources'
    | '/risk-assessment'
    | '/risk-profile'
    | '/services'
    | '/sip-calculator'
    | '/terms'
    | '/transparency'
    | '/funds/$fundSlug'
    | '/funds'
    | '/api/public/fund-sync'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/data-status'
    | '/explore'
    | '/faq'
    | '/feedback'
    | '/funds'
    | '/goals'
    | '/grievance'
    | '/learn'
    | '/privacy'
    | '/process'
    | '/resources'
    | '/risk-assessment'
    | '/risk-profile'
    | '/services'
    | '/sip-calculator'
    | '/terms'
    | '/transparency'
    | '/funds/$fundSlug'
    | '/funds/'
    | '/api/public/fund-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DataStatusRoute: typeof DataStatusRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  FundsRoute: typeof FundsRouteWithChildren
  GoalsRoute: typeof GoalsRoute
  GrievanceRoute: typeof GrievanceRoute
  LearnRoute: typeof LearnRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  ResourcesRoute: typeof ResourcesRoute
  RiskAssessmentRoute: typeof RiskAssessmentRoute
  RiskProfileRoute: typeof RiskProfileRoute
  ServicesRoute: typeof ServicesRoute
  SipCalculatorRoute: typeof SipCalculatorRoute
  TermsRoute: typeof TermsRoute
  TransparencyRoute: typeof TransparencyRoute
  ApiPublicFundSyncRoute: typeof ApiPublicFundSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-status': {
      id: '/data-status'
      path: '/data-status'
      fullPath: '/data-status'
      preLoaderRoute: typeof DataStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance': {
      id: '/grievance'
      path: '/grievance'
      fullPath: '/grievance'
      preLoaderRoute: typeof GrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-assessment': {
      id: '/risk-assessment'
      path: '/risk-assessment'
      fullPath: '/risk-assessment'
      preLoaderRoute: typeof RiskAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-profile': {
      id: '/risk-profile'
      path: '/risk-profile'
      fullPath: '/risk-profile'
      preLoaderRoute: typeof RiskProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sip-calculator': {
      id: '/sip-calculator'
      path: '/sip-calculator'
      fullPath: '/sip-calculator'
      preLoaderRoute: typeof SipCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds/': {
      id: '/funds/'
      path: '/'
      fullPath: '/funds/'
      preLoaderRoute: typeof FundsIndexRouteImport
      parentRoute: typeof FundsRoute
    }
    '/funds/$fundSlug': {
      id: '/funds/$fundSlug'
      path: '/$fundSlug'
      fullPath: '/funds/$fundSlug'
      preLoaderRoute: typeof FundsFundSlugRouteImport
      parentRoute: typeof FundsRoute
    }
    '/api/public/fund-sync': {
      id: '/api/public/fund-sync'
      path: '/api/public/fund-sync'
      fullPath: '/api/public/fund-sync'
      preLoaderRoute: typeof ApiPublicFundSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FundsRouteChildren {
  FundsFundSlugRoute: typeof FundsFundSlugRoute
  FundsIndexRoute: typeof FundsIndexRoute
}

const FundsRouteChildren: FundsRouteChildren = {
  FundsFundSlugRoute: FundsFundSlugRoute,
  FundsIndexRoute: FundsIndexRoute,
}

const FundsRouteWithChildren = FundsRoute._addFileChildren(FundsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DataStatusRoute: DataStatusRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  FundsRoute: FundsRouteWithChildren,
  GoalsRoute: GoalsRoute,
  GrievanceRoute: GrievanceRoute,
  LearnRoute: LearnRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  ResourcesRoute: ResourcesRoute,
  RiskAssessmentRoute: RiskAssessmentRoute,
  RiskProfileRoute: RiskProfileRoute,
  ServicesRoute: ServicesRoute,
  SipCalculatorRoute: SipCalculatorRoute,
  TermsRoute: TermsRoute,
  TransparencyRoute: TransparencyRoute,
  ApiPublicFundSyncRoute: ApiPublicFundSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
