/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as RiskProfileRouteImport } from './routes/risk-profile'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SipCalculatorRouteImport } from './routes/sip-calculator'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as FundsIndexRouteImport } from './routes/funds.index'
import { Route as FundsFundSlugRouteImport } from './routes/funds.$fundSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskProfileRoute = RiskProfileRouteImport.update({
  id: '/risk-profile',
  path: '/risk-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SipCalculatorRoute = SipCalculatorRouteImport.update({
  id: '/sip-calculator',
  path: '/sip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsIndexRoute = FundsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FundsRoute,
} as any)
const FundsFundSlugRoute = FundsFundSlugRouteImport.update({
  id: '/$fundSlug',
  path: '/$fundSlug',
  getParentRoute: () => FundsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/funds': typeof FundsRouteWithChildren
  '/goals': typeof GoalsRoute
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/risk-profile': typeof RiskProfileRoute
  '/services': typeof ServicesRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/terms': typeof TermsRoute
  '/funds/$fundSlug': typeof FundsFundSlugRoute
  '/funds/': typeof FundsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/goals': typeof GoalsRoute
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/risk-profile': typeof RiskProfileRoute
  '/services': typeof ServicesRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/terms': typeof TermsRoute
  '/funds/$fundSlug': typeof FundsFundSlugRoute
  '/funds': typeof FundsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/funds': typeof FundsRouteWithChildren
  '/goals': typeof GoalsRoute
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/risk-profile': typeof RiskProfileRoute
  '/services': typeof ServicesRoute
  '/sip-calculator': typeof SipCalculatorRoute
  '/terms': typeof TermsRoute
  '/funds/$fundSlug': typeof FundsFundSlugRoute
  '/funds/': typeof FundsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/funds'
    | '/goals'
    | '/learn'
    | '/privacy'
    | '/process'
    | '/risk-profile'
    | '/services'
    | '/sip-calculator'
    | '/terms'
    | '/funds/$fundSlug'
    | '/funds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/goals'
    | '/learn'
    | '/privacy'
    | '/process'
    | '/risk-profile'
    | '/services'
    | '/sip-calculator'
    | '/terms'
    | '/funds/$fundSlug'
    | '/funds'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/funds'
    | '/goals'
    | '/learn'
    | '/privacy'
    | '/process'
    | '/risk-profile'
    | '/services'
    | '/sip-calculator'
    | '/terms'
    | '/funds/$fundSlug'
    | '/funds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FundsRoute: typeof FundsRouteWithChildren
  GoalsRoute: typeof GoalsRoute
  LearnRoute: typeof LearnRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  RiskProfileRoute: typeof RiskProfileRoute
  ServicesRoute: typeof ServicesRoute
  SipCalculatorRoute: typeof SipCalculatorRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-profile': {
      id: '/risk-profile'
      path: '/risk-profile'
      fullPath: '/risk-profile'
      preLoaderRoute: typeof RiskProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sip-calculator': {
      id: '/sip-calculator'
      path: '/sip-calculator'
      fullPath: '/sip-calculator'
      preLoaderRoute: typeof SipCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds/': {
      id: '/funds/'
      path: '/'
      fullPath: '/funds/'
      preLoaderRoute: typeof FundsIndexRouteImport
      parentRoute: typeof FundsRoute
    }
    '/funds/$fundSlug': {
      id: '/funds/$fundSlug'
      path: '/$fundSlug'
      fullPath: '/funds/$fundSlug'
      preLoaderRoute: typeof FundsFundSlugRouteImport
      parentRoute: typeof FundsRoute
    }
  }
}

interface FundsRouteChildren {
  FundsFundSlugRoute: typeof FundsFundSlugRoute
  FundsIndexRoute: typeof FundsIndexRoute
}

const FundsRouteChildren: FundsRouteChildren = {
  FundsFundSlugRoute: FundsFundSlugRoute,
  FundsIndexRoute: FundsIndexRoute,
}

const FundsRouteWithChildren = FundsRoute._addFileChildren(FundsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FundsRoute: FundsRouteWithChildren,
  GoalsRoute: GoalsRoute,
  LearnRoute: LearnRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  RiskProfileRoute: RiskProfileRoute,
  ServicesRoute: ServicesRoute,
  SipCalculatorRoute: SipCalculatorRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
